routes/web.php
<?php
if(version_compare(PHP_VERSION, '7.2.0', '>=')) {
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
}

setlocale(LC_TIME, 'es_GT.UTF-8','es_GT.ISO-8859-1','es_GT','es_ES','es_ES','spanish');
//Carbon
use Carbon\Carbon;
Carbon::setLocale('es');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();
Route::get('/', function () {
    return redirect('costProyectos');
});

//Muestra de chivos de controles listos para ser usados
Route::get('chivos', function () {
    return view('chivos.demo');
});

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('catCats', 'cat_catController');
    Route::resource('catItems', 'cat_itemController');
    Route::get('json/catalogo','cat_itemController@json');
    Route::get('itemdeshabilitado/{id}','cat_itemController@itemdeshabilitado');

    //cost loqueado

    //Controles geograficos
    Route::get('json/geo','geoController@mostrar_hijos');
    Route::resource('administracion','AdministracionController');
    Route::resource('sedes', 'sedeController');
    Route::post('edit_user/{id}','AdministracionController@edit_user');
    Route::get('reiniciar_password/{id}','AdministracionController@reiniciar_password');
    Route::get('reiniciar_password_perfil/{id}','AdministracionController@reiniciar_password_perfil');
    Route::get('password_perfil_change/{id}','AdministracionController@password_perfil_change');
    Route::post('password_change','AdministracionController@password_change');
    Route::get('password_deshabilitar/{id}','AdministracionController@password_deshabilitar');
    Route::get('password_habilitar/{id}','AdministracionController@password_habilitar');


    //upload de fotografias del proyecto
    Route::get('image_upload','ImageController@imageUpload');
    Route::post('image_upload_save','ImageController@imageUploadPost');
    Route::post('eliminar_foto/{id}','ImageController@eliminar_foto');

    //publicador
    Route::get('publicar_proyecto/{id}','cost_proyectoController@publicar_proyecto');
    Route::get('no_publicar_proyecto/{id}','cost_proyectoController@no_publicar_proyecto');

    //seguimiento
    Route::get('marcar_seguimiento/{id}','cost_proyectoController@marcar_seguimiento');
    Route::get('no_marcar_seguimiento/{id}','cost_proyectoController@no_marcar_seguimiento');

    Route::resource('documentos', 'documentoController');
    Route::resource('empleos', 'empleoController');
    Route::get('identificacionProyecto/{id}', 'cost_proyectoController@detalle_plano_ident_proyecto');
    Route::resource('costProyectoDisPlans', 'cost_proyecto_dis_planController');
    Route::get('costProyectoDisPlans_plano', 'cost_proyecto_dis_planController@vista_plana');
    Route::resource('costProyectos', 'cost_proyectoController');
    Route::resource('costProyectoDisPlans', 'cost_proyecto_dis_planController');
    Route::resource('costProyectoPlanificas', 'cost_proyecto_planificaController');
    Route::resource('costProyectoSupervisions', 'cost_proyecto_supervisionController');
    Route::resource('costMetodologia','cost_metodologiaController');
    Route::resource('costProyectoDisPlans', 'cost_proyecto_dis_planController');
    Route::resource('costAmpliacions', 'cost_ampliacionController');
    Route::resource('costActas', 'cost_actaController');
    Route::resource('costAcuerdoFinanciamientos', 'cost_acuerdo_financiamientoController');
    Route::resource('costFianzas', 'cost_fianzaController');
    Route::resource('costInfoContratos', 'cost_info_contratoController');
    Route::resource('costPagoEfectuados', 'cost_pago_efectuadoController');
    Route::resource('descargaResponsables', 'descarga_responsableController');
    Route::resource('costLiquidacions', 'cost_liquidacionController');
    Route::resource('costLiquidacionAlcances', 'cost_liquidacion_alcanceController');
    Route::resource('costLiquidacionMontos', 'cost_liquidacion_montoController');
    Route::resource('costEstimacions', 'cost_estimacionController');
    Route::resource('costLiquidacionTiempos', 'cost_liquidacion_tiempoController');
    Route::resource('participantes', 'participanteController');
    Route::resource('costOferentes', 'cost_oferenteController');
    Route::resource('costOperadors', 'cost_operadorController');
    Route::resource('politicas', 'politicaController');
});
//rutas publicas
Route::resource('politicas', 'politicaController', [ 'only' => [ 'show'] ]);
Route::get("indicadores","indicadoresController@indicadores");
Route::resource('documentos', 'documentoController', [ 'only' => [ 'show','index' ] ]);
Route::resource('costProyectoDisPlans', 'cost_proyecto_dis_planController', [ 'only' => [ 'show' ,'index'] ]);
Route::resource('costProyectos', 'cost_proyectoController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costProyectoDisPlans', 'cost_proyecto_dis_planController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costProyectoPlanificas', 'cost_proyecto_planificaController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costProyectoSupervisions', 'cost_proyecto_supervisionController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costMetodologia', 'cost_metodologiaController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costProyectoDisPlans', 'cost_proyecto_dis_planController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costAmpliacions', 'cost_ampliacionController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costActas', 'cost_actaController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costAcuerdoFinanciamientos', 'cost_acuerdo_financiamientoController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costFianzas', 'cost_fianzaController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costInfoContratos', 'cost_info_contratoController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costPagoEfectuados', 'cost_pago_efectuadoController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('descargaResponsables', 'descarga_responsableController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costContactenos', 'cost_contactenosController');
Route::resource('costLiquidacions', 'cost_liquidacionController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costLiquidacionAlcances', 'cost_liquidacion_alcanceController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costLiquidacionMontos', 'cost_liquidacion_montoController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costEstimacions', 'cost_estimacionController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costLiquidacionTiempos', 'cost_liquidacion_tiempoController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('participantes', 'participanteController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costOferentes', 'cost_oferenteController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costOperadors', 'cost_operadorController', [ 'only' => [ 'show', 'index' ] ]);
Route::get('identificacionProyecto/{id}', 'cost_proyectoController@detalle_plano_ident_proyecto');
Route::get('download_oc4ids', 'cost_proyectoController@download_oc4ids');
Route::get('busqueda_especifica', 'cost_proyectoController@busqueda_especifica');
Route::post('busqueda_especifica', 'cost_proyectoController@busqueda_especifica');

//Pruebas
//Envio de correos
Route::get('/test/correo', 'emailController@test');

//convert json to csv
Route::get('convert_json_csv/{id}','cost_proyectoController@convert_json_csv');
Route::get('convert_json_excel/{id}','cost_proyectoController@convert_json_excel');
Route::get('costProyectos/proyecto/{id}','cost_proyectoController@ocds');
Route::post('costProyectos/proyectos_unificados','cost_proyectoController@ocds_unificado');

//Controles geograficos
Route::post('json/geo','geoController@mostrar_hijos');
Route::post('json/geo_todo','geoController@mostrar_hijos_con_todo');

app/Http/Controllers/descarga_responsableController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createdescarga_responsableRequest;
use App\Http\Requests\Updatedescarga_responsableRequest;
use App\Models\cost_proyecto;
use App\Models\descarga_responsable;
use App\Repositories\descarga_responsableRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use function Sodium\compare;

class descarga_responsableController extends AppBaseController
{
    /** @var  descarga_responsableRepository */
    private $descargaResponsableRepository;

    public function __construct(descarga_responsableRepository $descargaResponsableRepo)
    {
        $this->descargaResponsableRepository = $descargaResponsableRepo;

        // arreglo que contiene la configuracion del datatable variable que podra modificarse en la vista
        $this->data_table = [
            "searching"=>   false,
            "paging"=>   true,
            "ordering"=> false,
            "info"=>     false,
            "dom"=> 'Bfrtip',
            "buttons"=> [
                ["extend"=>"copy","className"=>"btn bg-gray","footer"=> true],
                ["extend"=>"excel","className"=>"btn bg-olive","footer"=> true],
                ["extend"=>"pdf","className"=>"btn bg-red","footer"=> true],
                ["extend"=>"print","className"=>"btn bg-yellow","footer"=> true]
            ],
            "language"=> [
                "url" => url('/js/reportes/data_tables/language/Spanish.json'),
                "buttons"=> [
                    "copyTitle" =>'Copiado',
                    "copyKeys"=> 'Preciona <i>ctrl</i> ou <i>\u2318</i> + <i>C</i> para copiar los datos de la tabla a su portapapeles. <br><br>Para cancelar, haga clic en este mensaje o presione Esc.',
                    "copySuccess" => ["_"=> '%d Filas Copiadas  ',1=>'1 Fila Copiada'],
                    "copy" =>'<i class="fa fa-copy"></i> Copiar',
                    "excel"=>'<i class="fa fa-file-excel-o"></i> Excel',
                    "pdf"=>'<i class="fa fa-file-pdf-o"></i> PDF',
                    "print"=>'<i class="fa fa-print"></i> Imprimir',
                ]
            ]

        ];
    }

    /**
     * Display a listing of the descarga_responsable.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        if (isset($request)){
            $url =url()->full();
            $explode = explode('?',$url);
            if (isset($explode[1])){
                $id_proyecto = $explode[1];
                $descargaResponsables = descarga_responsable::where('id_proyecto',$id_proyecto)->get();
            }else{
                $this->descargaResponsableRepository->pushCriteria(new RequestCriteria($request));
                $descargaResponsables = $this->descargaResponsableRepository->all();
            }
        }else{
            $this->descargaResponsableRepository->pushCriteria(new RequestCriteria($request));
            $descargaResponsables = $this->descargaResponsableRepository->all();
        }

        return view('descarga_responsables.index')
            ->with('descargaResponsables', $descargaResponsables);
    }

    /**
     * Show the form for creating a new descarga_responsable.
     *
     * @return Respons
     */
    public function create()
    {
        return view('descarga_responsables.create');
    }

    /**
     * Store a newly created descarga_responsable in storage.
     *
     * @param Createdescarga_responsableRequest $request
     *
     * @return Response
     */
    public function store(Createdescarga_responsableRequest $request)
    {
        $input = $request->all();
        #try cat del insert sino que muestre muestre mensaje rediccion al index
        try {
            #guarda datos del que descarga
                $descargaResponsable = $this->descargaResponsableRepository->create($input);
            #buscar datos de la descarga
                if (isset($request->general)){//descarga todos proyecto
                    $tipo_descarga = 1;
                    $array_resultado = cost_proyecto::busca_datos_proyecto_descarga(0,$tipo_descarga);
                }else{//descarga proyecto especifico
                    $tipo_descarga = 2;
                    $array_resultado = cost_proyecto::busca_datos_proyecto_descarga($request->id_proyecto,$tipo_descarga);
                }

        }
        catch (\Exception $e) {
            $array_resultado=[];
            $array_resultado['proyecto']=false;
            $array_resultado['proyecto_error']=$e->getMessage();
            $array_resultado['proyecto_mensaje']=null;
        }


        // se declara variable $json_data_table y se asigna valor de la variabel global data_table transformado en json pasa su uso en las vistas de reporteria
        $json_data_table = base64_encode(collect($this->data_table)->toJson());
        return view('descarga_responsables.descarga_excel',compact('array_resultado','json_data_table','tipo_descarga'));
    }

    /**
     * Display the specified descarga_responsable.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        try {
            #buscar datos de la descarga
            if ($id == 'general') {//descarga todos proyecto
                $tipo_descarga = 1;
                $array_resultado = cost_proyecto::busca_datos_proyecto_descarga(0, $tipo_descarga);
            } else {//descarga proyecto especifico
                $tipo_descarga = 2;
                $array_resultado = cost_proyecto::busca_datos_proyecto_descarga($id, $tipo_descarga);
            }

        } catch (\Exception $e) {
            $array_resultado = [];
            $array_resultado['proyecto'] = false;
            $array_resultado['proyecto_error'] = $e->getMessage();
            $array_resultado['proyecto_mensaje'] = null;
        }


        // se declara variable $json_data_table y se asigna valor de la variabel global data_table transformado en json pasa su uso en las vistas de reporteria
        $json_data_table = base64_encode(collect($this->data_table)->toJson());
        return view('descarga_responsables.descarga_excel', compact('array_resultado', 'json_data_table', 'tipo_descarga'));
    }
    /**
     * Show the form for editing the specified descarga_responsable.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $descargaResponsable = $this->descargaResponsableRepository->findWithoutFail($id);

        if (empty($descargaResponsable)) {
            Flash::error('Descarga Responsable not found');

            return redirect(route('descargaResponsables.index'));
        }

        return view('descarga_responsables.edit')->with('descargaResponsable', $descargaResponsable);
    }

    /**
     * Update the specified descarga_responsable in storage.
     *
     * @param  int              $id
     * @param Updatedescarga_responsableRequest $request
     *
     * @return Response
     */
    public function update($id, Updatedescarga_responsableRequest $request)
    {
        $descargaResponsable = $this->descargaResponsableRepository->findWithoutFail($id);

        if (empty($descargaResponsable)) {
            Flash::error('Descarga Responsable not found');

            return redirect(route('descargaResponsables.index'));
        }

        $descargaResponsable = $this->descargaResponsableRepository->update($request->all(), $id);

        Flash::success('Descarga Responsable updated successfully.');

        return redirect(route('descargaResponsables.index'));
    }

    /**
     * Remove the specified descarga_responsable from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $descargaResponsable = $this->descargaResponsableRepository->findWithoutFail($id);

        if (empty($descargaResponsable)) {
            Flash::error('Descarga Responsable not found');

            return redirect(route('descargaResponsables.index'));
        }

        $this->descargaResponsableRepository->delete($id);

        Flash::success('Descarga Responsable deleted successfully.');

        return redirect(route('descargaResponsables.index'));
    }
}

resources/views/descarga_responsables/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Descarga Responsable
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'descargaResponsables.store']) !!}

                        @include('descarga_responsables.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/descarga_responsables/descarga_excel.blade.php
@extends('layouts.app')
@include('reportes._style')
@push('styles')
    <link rel="stylesheet" href="{{ url("/css/reportes/bootstrap-datetimepicker/bootstrap-datetimepicker.css") }}">
    <link rel="stylesheet" href="{{ url("/css/reportes/datatables/fixedColumns.dataTables.min.css") }}">
    <link rel="stylesheet" href="{{ url("/css/reportes/datatables/buttons.dataTables.css") }}">
@endpush
@push('javascript')
    <script src="{{ url('/js/reportes/data_tables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ url('/js/reportes/data_tables/dataTables.buttons.min.js') }}"></script>
    <script src="{{ url('/js/reportes/data_tables/buttons.flash.min.js') }}"></script>
    <script src="{{ url('/js/reportes/data_tables/jszip.min.js') }}"></script>
    <script src="{{ url('/js/reportes/data_tables/pdfmake.min.js') }}"></script>
    <script src="{{ url('/js/reportes/data_tables/vfs_fonts.js') }}"></script>
    <script src="{{ url('/js/reportes/data_tables/buttons.html5.min.js') }}"></script>
    <script src="{{ url('/js/reportes/data_tables/buttons.print.min.js') }}"></script>

    <script type="text/javascript">
        var base64_data_table = '{!! $json_data_table !!}';
        var json_data_table = JSON.parse(atob(base64_data_table));
        console.log(json_data_table);
    </script>
@endpush
@section('content')
    <div class="content">
        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">
                    <a href="{{ URL::previous() }}" class="btn btn-primary  no-print btn-sm"><i class="fa fa-reply" aria-hidden="true"></i>Ir atrás</a>
                    <b>  <i class="fa fa-download" aria-hidden="true"></i> Decarga del proyecto </b>
                </h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>

            <div class="box-body table-responsive">
                <div class="table-responsive col-md-12">
                    <table  id="tabla_proyecto" class="table table-bordered">
                        <thead>
                            <tr>
                                @foreach($array_resultado[0] as $key => $val)
                                    <th>{{$key}}</th>
                                @endforeach
                            </tr>
                        </thead>
                        <tbody>
                            @if($tipo_descarga == 1)
                                @foreach(collect ($array_resultado) as $key => $val)
                                    <tr>
                                        @foreach($val as $k =>$v)
                                            <td>{{$v}}</td>
                                        @endforeach
                                    </tr>
                                @endforeach
                            @else
                                @foreach($array_resultado[0] as $key => $val)
                                    <td>{{$val}}</td>
                                @endforeach
                            @endif

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('javascript')
    <script type="text/javascript">
        $(document).ready(function() {
            $('#tabla_proyecto').DataTable(json_data_table);
        } );
    </script>
@endpush

resources/views/descarga_responsables/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Descarga Responsable
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($descargaResponsable, ['route' => ['descargaResponsables.update', $descargaResponsable->id], 'method' => 'patch']) !!}

                        @include('descarga_responsables.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/descarga_responsables/fields.blade.php
<!-- Nombre Completo Field -->
<div class="form-group col-sm-12">
    {!! Form::label('nombre_completo', '* Nombre completo:') !!}
    {!! Form::text('nombre_completo', null, ['class' => 'form-control','required' => 'required']) !!}
</div>

<!-- No Identificacion Personal Field -->
<div class="form-group col-sm-12">
    {!! Form::label('no_identificacion_personal', '* No Identificación personal:', ['class'=>'required']) !!}
    {!! Form::text('no_identificacion_personal', null, ['class' => 'form-control required', 'required' => 'required']) !!}
</div>

<!-- Descripcion Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('descripcion', '* Descripción:') !!}
    {!! Form::textarea('descripcion', null, ['class' => 'form-control', 'required' => 'required']) !!}
</div>

<!-- Fh Descarga Field -->
<div class="form-group col-sm-6">
    {!! Form::hidden('fh_descarga', \Carbon\Carbon::now()->format('Y-m-d'), ['class' => 'form-control']) !!}
</div>

@if(isset($bnd_gnrl) && $bnd_gnrl == 2)
    <!-- Id Proyecto Field -->
    <div class="form-group col-sm-6">
        {!! Form::hidden('id_proyecto', $costProyecto->id, ['class' => 'form-control']) !!}
    </div>
@else
    {!! Form::hidden('id_proyecto',0, ['class' => 'form-control']) !!}
    {!! Form::hidden('general',1, ['class' => 'form-control']) !!}
@endif

resources/views/descarga_responsables/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Descarga Responsables</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('descargaResponsables.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('descarga_responsables.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/descarga_responsables/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Descarga Responsable
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('descarga_responsables.show_fields')
                    <a href="{!! route('descargaResponsables.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/descarga_responsables/show_fields.blade.php
<!-- Id Descarga Responsable Field -->
<div class="form-group">
    {!! Form::label('id_descarga_responsable', 'Id Descarga Responsable:') !!}
    <p>{!! $descargaResponsable->id_descarga_responsable !!}</p>
</div>

<!-- Nombre Completo Field -->
<div class="form-group">
    {!! Form::label('nombre_completo', 'Nombre Completo:') !!}
    <p>{!! $descargaResponsable->nombre_completo !!}</p>
</div>

<!-- No Identificacion Personal Field -->
<div class="form-group">
    {!! Form::label('no_identificacion_personal', 'No Identificacion Personal:') !!}
    <p>{!! $descargaResponsable->no_identificacion_personal !!}</p>
</div>

<!-- Descripcion Field -->
<div class="form-group">
    {!! Form::label('descripcion', 'Descripcion:') !!}
    <p>{!! $descargaResponsable->descripcion !!}</p>
</div>

<!-- Fh Descarga Field -->
<div class="form-group">
    {!! Form::label('fh_descarga', 'Fh Descarga:') !!}
    <p>{!! $descargaResponsable->fh_descarga !!}</p>
</div>

<!-- Id Proyecto Field -->
<div class="form-group">
    {!! Form::label('id_proyecto', 'Id Proyecto:') !!}
    <p>{!! $descargaResponsable->id_proyecto !!}</p>
</div>

resources/views/descarga_responsables/table.blade.php
<table class="table table-responsive" id="descargaResponsables-table">
    <thead>
        <tr>
            <th>Nombre Completo</th>
        <th>No Identificacion Personal</th>
        <th>Descripcion</th>
        <th>Fh Descarga</th>
        <th>Id Proyecto</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($descargaResponsables as $descargaResponsable)
        <tr>
            <td>{!! $descargaResponsable->nombre_completo !!}</td>
            <td>{!! $descargaResponsable->no_identificacion_personal !!}</td>
            <td>{!! $descargaResponsable->descripcion !!}</td>
            <td>{!! $descargaResponsable->fh_descarga !!}</td>
            <td>{!! $descargaResponsable->id_proyecto !!}</td>
            <td>
                {!! Form::open(['route' => ['descargaResponsables.destroy', $descargaResponsable->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('descargaResponsables.show', [$descargaResponsable->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('descargaResponsables.edit', [$descargaResponsable->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>