routes/web.php
<?php
if(version_compare(PHP_VERSION, '7.2.0', '>=')) {
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
}

setlocale(LC_TIME, 'es_GT.UTF-8','es_GT.ISO-8859-1','es_GT','es_ES','es_ES','spanish');
//Carbon
use Carbon\Carbon;
Carbon::setLocale('es');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();
Route::get('/', function () {
    return redirect('costProyectos');
});

//Muestra de chivos de controles listos para ser usados
Route::get('chivos', function () {
    return view('chivos.demo');
});

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('catCats', 'cat_catController');
    Route::resource('catItems', 'cat_itemController');
    Route::get('json/catalogo','cat_itemController@json');
    Route::get('itemdeshabilitado/{id}','cat_itemController@itemdeshabilitado');

    //cost loqueado

    //Controles geograficos
    Route::get('json/geo','geoController@mostrar_hijos');
    Route::resource('administracion','AdministracionController');
    Route::resource('sedes', 'sedeController');
    Route::post('edit_user/{id}','AdministracionController@edit_user');
    Route::get('reiniciar_password/{id}','AdministracionController@reiniciar_password');
    Route::get('reiniciar_password_perfil/{id}','AdministracionController@reiniciar_password_perfil');
    Route::get('password_perfil_change/{id}','AdministracionController@password_perfil_change');
    Route::post('password_change','AdministracionController@password_change');
    Route::get('password_deshabilitar/{id}','AdministracionController@password_deshabilitar');
    Route::get('password_habilitar/{id}','AdministracionController@password_habilitar');


    //upload de fotografias del proyecto
    Route::get('image_upload','ImageController@imageUpload');
    Route::post('image_upload_save','ImageController@imageUploadPost');
    Route::post('eliminar_foto/{id}','ImageController@eliminar_foto');

    //publicador
    Route::get('publicar_proyecto/{id}','cost_proyectoController@publicar_proyecto');
    Route::get('no_publicar_proyecto/{id}','cost_proyectoController@no_publicar_proyecto');

    //seguimiento
    Route::get('marcar_seguimiento/{id}','cost_proyectoController@marcar_seguimiento');
    Route::get('no_marcar_seguimiento/{id}','cost_proyectoController@no_marcar_seguimiento');

    Route::resource('documentos', 'documentoController');
    Route::resource('empleos', 'empleoController');
    Route::get('identificacionProyecto/{id}', 'cost_proyectoController@detalle_plano_ident_proyecto');
    Route::resource('costProyectoDisPlans', 'cost_proyecto_dis_planController');
    Route::get('costProyectoDisPlans_plano', 'cost_proyecto_dis_planController@vista_plana');
    Route::resource('costProyectos', 'cost_proyectoController');
    Route::resource('costProyectoDisPlans', 'cost_proyecto_dis_planController');
    Route::resource('costProyectoPlanificas', 'cost_proyecto_planificaController');
    Route::resource('costProyectoSupervisions', 'cost_proyecto_supervisionController');
    Route::resource('costMetodologia','cost_metodologiaController');
    Route::resource('costProyectoDisPlans', 'cost_proyecto_dis_planController');
    Route::resource('costAmpliacions', 'cost_ampliacionController');
    Route::resource('costActas', 'cost_actaController');
    Route::resource('costAcuerdoFinanciamientos', 'cost_acuerdo_financiamientoController');
    Route::resource('costFianzas', 'cost_fianzaController');
    Route::resource('costInfoContratos', 'cost_info_contratoController');
    Route::resource('costPagoEfectuados', 'cost_pago_efectuadoController');
    Route::resource('descargaResponsables', 'descarga_responsableController');
    Route::resource('costLiquidacions', 'cost_liquidacionController');
    Route::resource('costLiquidacionAlcances', 'cost_liquidacion_alcanceController');
    Route::resource('costLiquidacionMontos', 'cost_liquidacion_montoController');
    Route::resource('costEstimacions', 'cost_estimacionController');
    Route::resource('costLiquidacionTiempos', 'cost_liquidacion_tiempoController');
    Route::resource('participantes', 'participanteController');
    Route::resource('costOferentes', 'cost_oferenteController');
    Route::resource('costOperadors', 'cost_operadorController');
    Route::resource('politicas', 'politicaController');
});
//rutas publicas
Route::resource('politicas', 'politicaController', [ 'only' => [ 'show'] ]);
Route::get("indicadores","indicadoresController@indicadores");
Route::resource('documentos', 'documentoController', [ 'only' => [ 'show','index' ] ]);
Route::resource('costProyectoDisPlans', 'cost_proyecto_dis_planController', [ 'only' => [ 'show' ,'index'] ]);
Route::resource('costProyectos', 'cost_proyectoController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costProyectoDisPlans', 'cost_proyecto_dis_planController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costProyectoPlanificas', 'cost_proyecto_planificaController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costProyectoSupervisions', 'cost_proyecto_supervisionController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costMetodologia', 'cost_metodologiaController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costProyectoDisPlans', 'cost_proyecto_dis_planController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costAmpliacions', 'cost_ampliacionController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costActas', 'cost_actaController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costAcuerdoFinanciamientos', 'cost_acuerdo_financiamientoController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costFianzas', 'cost_fianzaController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costInfoContratos', 'cost_info_contratoController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costPagoEfectuados', 'cost_pago_efectuadoController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('descargaResponsables', 'descarga_responsableController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costContactenos', 'cost_contactenosController');
Route::resource('costLiquidacions', 'cost_liquidacionController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costLiquidacionAlcances', 'cost_liquidacion_alcanceController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costLiquidacionMontos', 'cost_liquidacion_montoController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costEstimacions', 'cost_estimacionController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costLiquidacionTiempos', 'cost_liquidacion_tiempoController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('participantes', 'participanteController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costOferentes', 'cost_oferenteController', [ 'only' => [ 'show', 'index' ] ]);
Route::resource('costOperadors', 'cost_operadorController', [ 'only' => [ 'show', 'index' ] ]);
Route::get('identificacionProyecto/{id}', 'cost_proyectoController@detalle_plano_ident_proyecto');
Route::get('download_oc4ids', 'cost_proyectoController@download_oc4ids');
Route::get('busqueda_especifica', 'cost_proyectoController@busqueda_especifica');
Route::post('busqueda_especifica', 'cost_proyectoController@busqueda_especifica');

//Pruebas
//Envio de correos
Route::get('/test/correo', 'emailController@test');

//convert json to csv
Route::get('convert_json_csv/{id}','cost_proyectoController@convert_json_csv');
Route::get('convert_json_excel/{id}','cost_proyectoController@convert_json_excel');
Route::get('costProyectos/proyecto/{id}','cost_proyectoController@ocds');
Route::post('costProyectos/proyectos_unificados','cost_proyectoController@ocds_unificado');

//Controles geograficos
Route::post('json/geo','geoController@mostrar_hijos');
Route::post('json/geo_todo','geoController@mostrar_hijos_con_todo');

app/Http/Controllers/cost_info_contratoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createcost_info_contratoRequest;
use App\Http\Requests\Updatecost_info_contratoRequest;
use App\Models\cat_item;
use App\Repositories\cost_info_contratoRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash; // rewrite this line

use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class cost_info_contratoController extends AppBaseController {

    /** @var  cost_info_contratoRepository */
    private $costInfoContratoRepository;

    public function __construct(cost_info_contratoRepository $costInfoContratoRepo)
    {
        $this->costInfoContratoRepository = $costInfoContratoRepo;
    }

    /**
     * Display a listing of the cost_info_contrato.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $this->costInfoContratoRepository->pushCriteria(new RequestCriteria($request));
        $costInfoContratos = $this->costInfoContratoRepository->all();

        return view('cost_info_contratos.index')
            ->with('costInfoContratos', $costInfoContratos);
    }

    /**
     * Show the form for creating a new cost_info_contrato.
     *
     * @return Response
     */
    public function create(Request $request)
    {
        $bnd_edit = false;
        $id_proyecto = $request->id_proyecto;
        $id_fase = $request->id_fase;
        $tipo = $request->tipo;
        return view('cost_info_contratos.create', compact('bnd_edit', 'id_proyecto', 'id_fase', 'tipo'));
    }

    /**
     * Store a newly created cost_info_contrato in storage.
     *
     * @param Createcost_info_contratoRequest $request
     *
     * @return Response
     */
    public function store(Createcost_info_contratoRequest $request)
    {
        $input = $request->all();
        $input[ 'fecha_aprobacion_contrato' ] = $request->fecha_aprobacion_contrato_submit;
        $input[ 'fecha_nombramiento' ] = $request->fecha_nombramiento_submit;
        $input[ 'fecha_inicio' ] = $request->fecha_inicio_submit;
        $input[ 'fecha_contrato' ] = $request->fecha_contrato_submit;
        $input[ 'fecha_publicacion' ] = $request->fecha_publicacion_submit;
        $input[ 'fecha_ultima_mod_gc' ] = $request->fecha_ultima_mod_gc_submit;
        $input[ 'fecha_autoriza_bitacora' ] = $request->fecha_autoriza_bitacora_submit;
        $input[ 'fecha_inicio_ejecucion' ] = $request->fecha_inicio_ejecucion_submit;
        $input[ 'estado_contrato_oc_d' ] = isset($request->estado_contrato_oc)?cat_item::find($request->estado_contrato_oc)->descripcion:null;
        unset($input[ 'fecha_autoriza_bitacora_submit' ],$input[ 'fecha_ultima_mod_gc_submit' ], $input[ 'fecha_publicacion_submit' ],$input[ 'fecha_aprobacion_contrato_submit' ], $input[ 'fecha_nombramiento_submit' ], $input[ 'fecha_inicio_submit' ], $input[ 'fecha_contrato_submit' ]);

        $input[ 'fecha_inicio_ejecucion' ] = $request->fecha_inicio_ejecucion_submit;
        $input[ 'fecha_fin_ejecucion' ] = $request->fecha_fin_ejecucion_submit;
        $input[ 'metodo_procuracion' ] = $request->metodo_procuracion;
        $input[ 'costo_estimado_moneda' ] = $request->costo_estimado_moneda;
        $input[ 'costo_estimado' ] = $request->costo_estimado;
        $input[ 'moneda_final' ] = $request->moneda_final;
        $input[ 'precio_contrato_final' ] = $request->precio_contrato_final;

        $costInfoContrato = $this->costInfoContratoRepository->create($input);

        Flash::success('La Información del  Contrato se creó exitosamente');
        return redirect(route('costInfoContratos.show', [ $costInfoContrato->id ]));

    }

    /**
     * Display the specified cost_info_contrato.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $costInfoContrato = $this->costInfoContratoRepository->findWithoutFail($id);
        if (empty($costInfoContrato)) {
            Flash::error('Cost Info Contrato not found');
            return redirect(route('costInfoContratos.index'));
        }
        return view('cost_info_contratos.show')->with('costInfoContrato', $costInfoContrato);
    }

    /**
     * Show the form for editing the specified cost_info_contrato.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $costInfoContrato = $this->costInfoContratoRepository->findWithoutFail($id);
        $id_fase = $costInfoContrato->id_fase;
        $bnd_edit = true;
        if (empty($costInfoContrato)) {
            Flash::error('Cost Info Contrato not found');

            return redirect(route('costInfoContratos.index'));
        }

        return view('cost_info_contratos.edit', compact('bnd_edit','id_fase'))->with('costInfoContrato', $costInfoContrato);
    }

    /**
     * Update the specified cost_info_contrato in storage.
     *
     * @param  int $id
     * @param Updatecost_info_contratoRequest $request
     *
     * @return Response
     */
    public function update($id, Updatecost_info_contratoRequest $request)
    {//dd($request);
        $costInfoContrato = $this->costInfoContratoRepository->findWithoutFail($id);
        $input = $request->all();
        $input[ 'fecha_aprobacion_contrato' ] = $request->fecha_aprobacion_contrato_submit;
        $input[ 'fecha_nombramiento' ] = $request->fecha_nombramiento_submit;
        $input[ 'fecha_inicio' ] = $request->fecha_inicio_submit;
        $input[ 'fecha_contrato' ] = $request->fecha_contrato_submit;
        $input[ 'fecha_publicacion' ] = $request->fecha_publicacion_submit;
        $input[ 'fecha_ultima_mod_gc' ] = $request->fecha_ultima_mod_gc_submit;
        $input[ 'fecha_autoriza_bitacora' ] = $request->fecha_autoriza_bitacora_submit;
        $input[ 'fecha_inicio_ejecucion' ] = $request->fecha_inicio_ejecucion_submit;
        $input[ 'estado_contrato_oc_d' ] = isset($request->estado_contrato_oc)?cat_item::find($request->estado_contrato_oc)->descripcion:null;

        $input[ 'fecha_inicio_ejecucion' ] = $request->fecha_inicio_ejecucion_submit;
        $input[ 'fecha_fin_ejecucion' ] = $request->fecha_fin_ejecucion_submit;
        $input[ 'metodo_procuracion' ] = $request->metodo_procuracion;
        $input[ 'costo_estimado_moneda' ] = $request->costo_estimado_moneda;
        $input[ 'costo_estimado' ] = $request->costo_estimado;
        $input[ 'moneda_final' ] = $request->moneda_final;
        $input[ 'precio_contrato_final' ] = $request->precio_contrato_final;

        unset($input[ 'fecha_aprobacion_contrato_submit' ], $input[ 'fecha_nombramiento_submit' ], $input[ 'fecha_inicio_submit' ], $input[ 'fecha_contrato_submit' ]);

        if (empty($costInfoContrato)) {
            Flash::error('Cost Info Contrato not found                  ');

            return redirect(route('costInfoContratos.index'));
        }
        $costInfoContrato = $this->costInfoContratoRepository->update($input,$id);

        Flash::success('La Información del  Contrato se actualizó exitosamente.');
        return redirect(route('costInfoContratos.show', [ $costInfoContrato->id ]));
    }

    /**
     * Remove the specified cost_info_contrato from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $costInfoContrato = $this->costInfoContratoRepository->findWithoutFail($id);

        if (empty($costInfoContrato)) {
            Flash::error('Cost Info Contrato not found');

            return redirect(route('costInfoContratos.index'));
        }
        $id_proyecto =$costInfoContrato->id_proyecto;
        $this->costInfoContratoRepository->delete($id);

        Flash::success('Información del  Contrato eliminada exitosamente.');

        return redirect(route('costProyectos.show', ['id_proyecto'=>$id_proyecto,'a'=>1]));
    }
}

resources/views/cost_info_contratos/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
           Nueva Información del Contrato
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'costInfoContratos.store']) !!}

                        @include('cost_info_contratos.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cost_info_contratos/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Cost Info Contrato
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($costInfoContrato, ['route' => ['costInfoContratos.update', $costInfoContrato->id], 'method' => 'patch']) !!}

                        @include('cost_info_contratos.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/cost_info_contratos/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Cost Info Contratos</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('costInfoContratos.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('cost_info_contratos.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/cost_info_contratos/show.blade.php
@extends('layouts.app')
@section('content')
    @include('flash::message')
    <section class="content-header">
        <h1>
            Información del Contrato
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('cost_info_contratos.show_fields')
                </div>
                <div class="text-left">
                    <a href="{!! route('costProyectos.show', [$costInfoContrato->id_proyecto,'a'=>1]) !!}"
                       class="btn btn-default">Atrás</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cost_info_contratos/table.blade.php
<table class="table table-responsive" id="costInfoContratos-table">
    <thead>
        <tr>
            <th>Id Proyecto</th>
        <th>Tipo</th>
        <th>Estado Contrado</th>
        <th>Plazo Contrato</th>
        <th>Tipo Numero Contrato</th>
        <th>Fecha Inicio</th>
        <th>Empresa Constructora</th>
        <th>Objeto Contrato</th>
        <th>No Precalificado</th>
        <th>Fecha Actualizacion</th>
        <th>Precio Contrato</th>
        <th>Fecha Contrato</th>
        <th>Aprobacion Contrato</th>
        <th>Fecha Aprobacion Contrato</th>
        <th>Nombre Firma</th>
        <th>Cargo Firma</th>
        <th>Nombramiento</th>
        <th>Fecha Nombramiento</th>
        <th>Conclusion</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($costInfoContratos as $costInfoContrato)
        <tr>
            <td>{!! $costInfoContrato->id_proyecto !!}</td>
            <td>{!! $costInfoContrato->tipo !!}</td>
            <td>{!! $costInfoContrato->estado_contrado !!}</td>
            <td>{!! $costInfoContrato->plazo_contrato !!}</td>
            <td>{!! $costInfoContrato->tipo_numero_contrato !!}</td>
            <td>{!! $costInfoContrato->fecha_inicio !!}</td>
            <td>{!! $costInfoContrato->empresa_constructora !!}</td>
            <td>{!! $costInfoContrato->objeto_contrato !!}</td>
            <td>{!! $costInfoContrato->no_precalificado !!}</td>
            <td>{!! $costInfoContrato->fecha_actualizacion !!}</td>
            <td>{!! $costInfoContrato->precio_contrato !!}</td>
            <td>{!! $costInfoContrato->fecha_contrato !!}</td>
            <td>{!! $costInfoContrato->aprobacion_contrato !!}</td>
            <td>{!! $costInfoContrato->fecha_aprobacion_contrato !!}</td>
            <td>{!! $costInfoContrato->nombre_firma !!}</td>
            <td>{!! $costInfoContrato->cargo_firma !!}</td>
            <td>{!! $costInfoContrato->nombramiento !!}</td>
            <td>{!! $costInfoContrato->fecha_nombramiento !!}</td>
            <td>{!! $costInfoContrato->conclusion !!}</td>
            <td>
                {!! Form::open(['route' => ['costInfoContratos.destroy', $costInfoContrato->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('costInfoContratos.show', [$costInfoContrato->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('costInfoContratos.edit', [$costInfoContrato->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>